### ISSUE TITLE
Failure when downloading the ShapeNet Data

### ISSUE THREAD

**Issue by YoruCathy** [itailang/SampleNet#1]
When I was trying to start the reconstructing task, it seems the auto downloading failed.
![image](https://user-images.githubusercontent.com/16759982/79010852-63077c80-7b95-11ea-935b-4ea1dac54101.png)
I downloaded the zip file from dropbox manually and it works. Is it due to the network issue or something is wrong with the code?

**Comment by itailang** [comment]
Dear Cathy,
Thank you for your interest in our work. It is probably a network issue. For your convenience, I added to the repository a [script](https://github.com/itailang/SampleNet/blob/master/reconstruction/download_data.sh) for downloading the data and instructions in the [reconstruction readme file](https://github.com/itailang/SampleNet/blob/master/reconstruction/README.md).
