### ISSUE TITLE
NameError: name 'farthest_point_sample' is not defined

### ISSUE THREAD

**Issue by ZhangYi0810** [itailang/SampleNet#10]
Hey,When I train the Autoencoder model,the error shows NameError: name 'farthest_point_sample' is not defined
 @itailang @asafmanor

**Comment by itailang** [comment]
Hello @Yerless,

Please compile the farthest point sampling op using [this compilation script](https://github.com/itailang/SampleNet/blob/master/reconstruction/external/sampling/tf_sampling_compile.sh), before training the autoencoder. Note that you should have cuda installed on your machine, and you should refer to its folder in the script (currently it refers to cuda-10.0).

**Comment by ZhangYi0810** [comment]
Thanks for your advice,I will continue to read your code

**Comment by itailang** [comment]
With pleasure! Please share any further issues you might encounter.
