### ISSUE TITLE
Whether the SampleNet is suitable for large scene data sets like semantic3d or KITTI?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [itailang/SampleNet#11]

**Comment by itailang** [comment]
Dear @Yellowshuohahaha,

Basically yes. The question is which task you want to perform. If the task's output is independent of number of input points, as for object detection, then SampleNet fits naturally. For semantic segmentation, where there is an output per point, a propagation module from the sampled points to the non-sampled ones should be added.

You are welcome to share any further questions you may have about this subject or others.

**Comment by Yellowshuohahaha** [comment]
Get it, thanks a lot!
