### ISSUE TITLE
What does "Classification accuracy" mean in the paper? 

### ISSUE THREAD

**Issue by jamekuma** [itailang/SampleNet#13]
Thanks for your great contributions on point cloud downsampling. What does "Classification accuracy" mean in the paper?  Is it corresponding to "eval accuracy" or "eval avg class acc"? 

Thank you for your reply.

**Comment by itailang** [comment]
Dear @jamekuma,

Thank you for your interest in our work. "Classification accuracy" is "eval accuracy".
