### ISSUE TITLE
Can SampleNet obtain better performance on Semantic Segmentation task?

### ISSUE THREAD

**Issue by whuhxb** [itailang/SampleNet#14]
Hi Authors:

     I have one question. Can the proposed SampleNet be used on 3D Point Cloud Semantic Segmentation and obtain better performances on 3D Point Cloud Semantic Segmentation task? Thanks.
 
Xiaobing

**Comment by itailang** [comment]
Dear @whuhxb,

You may use competitive instances of SampleNet for the task of 3D Point Cloud Semantic Segmentation. Please see a recent work related to this subject: [Unsupervised Point Cloud Object Co-segmentation by
Co-contrastive Learning and Mutual Attention Sampling](https://openaccess.thecvf.com/content/ICCV2021/papers/Yang_Unsupervised_Point_Cloud_Object_Co-Segmentation_by_Co-Contrastive_Learning_and_Mutual_ICCV_2021_paper.pdf).

**Comment by whuhxb** [comment]
> Dear @whuhxb,
> 
> You may use competitive instances of SampleNet for the task of 3D Point Cloud Semantic Segmentation. Please see a recent related work on this subject: [Unsupervised Point Cloud Object Co-segmentation by Co-contrastive Learning and Mutual Attention Sampling](https://openaccess.thecvf.com/content/ICCV2021/papers/Yang_Unsupervised_Point_Cloud_Object_Co-Segmentation_by_Co-Contrastive_Learning_and_Mutual_ICCV_2021_paper.pdf).

OK. Thanks a lot. I will read this paper.

**Comment by whuhxb** [comment]
@itailang  @asafmanor 
Hi, I have read this paper. This paper is mainly for unsupervised co-segmentation by constructing co-constrastive learning loss. Can SampleNet be applied only on supervised segmentation, and can obtain better performance than FPS or random sampling? Thanks a lot.

**Comment by itailang** [comment]
@whuhxb,

We have not tried it. You are welcome to do that and share your  thoughts.
