### ISSUE TITLE
problem with knn_cuda torch 

### ISSUE THREAD

**Issue by LEEHK96** [itailang/SampleNet#15]
Thank you for sharing great work. I wonder why this issue is occured

soft_projection.py

```

    def _get_distances(self, grouped_points, query_cloud):
        deltas = grouped_points - query_cloud.unsqueeze(-1).expand_as(grouped_points)
        dist = torch.sum(deltas ** 2, dim=_axis_to_dim(3), keepdim=True) / self.sigma()
        return dist
```

`Traceback (most recent call last):
  File "soft_projection.py", line 262, in <module>
    projected_points = propagator.project(query_cloud_pl, point_cloud_pl)
  File "soft_projection.py", line 141, in project
    dist = self._get_distances(grouped_points, query_cloud)
  File "soft_projection.py", line 95, in _get_distances
    dist = torch.sum(deltas ** 2, dim=_axis_to_dim(3), keepdim=True) / self.sigma()
TypeError: 'Tensor' object is not callable`

help me! thank you

**Comment by itailang** [comment]
Dear @LEEHK96,

Thank you for your interest in our work.

The issue occurred since sigma was set in the SoftProjection test code snippet instead of the temperature. I have fixed this issue. Please pull the update code.
