### ISSUE TITLE
Difference test set accuracy of  train_samplenet.py and evaluate_samplenet.py in the classification task 

### ISSUE THREAD

**Issue by hay-001** [itailang/SampleNet#17]
Why is the test set accuracy of train_samplenet.py much higher than  evaluate_samplenet.py in the classification task?

**Comment by itailang** [comment]
Dear @hay-001,

At the train phase, the test set accuracy is computed with the softly projected points, while at the evaluation phase, the sampled points are used. This change in the points can cause a difference in the accuracy result.

**Comment by XMU-qcj** [comment]
So why not use soft projection points in the evaluation stage?

**Comment by itailang** [comment]
Dear @Unknownnnnnnn,

Our problem statement is point cloud sampling. This is why we evaluate the performance with the sampled points.
