### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by ptxaxx** [itailang/SampleNet#18]
HI!
    First of all your ideas are very good, and thank you very much for sharing the code . I have a question：how should the registration results be visualized? I hope you can help me! THx

**Comment by itailang** [comment]
Dear @ptxaxx,
You may use the following function:
https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/reconstruction/src/general_utils.py#L141.

**Comment by ptxaxx** [comment]
> Dear @ptxaxx, You may use the following function:
> 
> https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/reconstruction/src/general_utils.py#L141
> 
> .

Thank you very much for your prompt reply！
Because my foundation is weak，so I don't know how to use this function；But I'm intrigued by the idea and can't wait to see the results of my own training；I follow the registration‘s readme to implement，The result obtained is as follows：
Experiment name: log/SAMPLENET64_model_best.pth
AUC = 0.9706000000000001
Mean rotation Error = 5.049964462220669
STD rotation Error = 7.385068412955796
Mean consistency Error = 0.005256387873087079
STD consistency Error = 0.0014876173671854744
done (PID=30554)

So can you give a detailed visualization step？Thank you very much, best wishes！

**Comment by itailang** [comment]
Your results seem very good.

Les't say your point cloud is my_pc. So, for visualization simply use:
plot_3d_point_cloud(my_pc).

You can configure the function's parameters to customize the plot for your preferences.

**Comment by ptxaxx** [comment]
Hi！Sorry to bother you again！
      I looked at the code you wrote, but I don't know how to modify the code to output the registration result！For example, output txt, ply, pcd, etc. I hope you can help me！ 
Best wishs！

**Comment by itailang** [comment]
Hi @ptxaxx,

The usage is pretty simple. Load your point cloud data according to the file format you saved it to. Then, convert the loaded point cloud to an Nx3 numpy array and use it for the plotting function.

**Comment by ptxaxx** [comment]
Hi!
Thanks for your prompt reply .
I don't know how to output the final registration result of point cloud data

**Comment by asafmanor** [comment]
Hi @ptxaxx 
During the test pass (`test1`) you can create a breakpoint **or** modify the code to visualize the point cloud.
For example, a breakpoint in `compute_pcrnet_loss` at line 573 will give you an option to visualize the following:

`p0` = original point cloud
`p1` = rotated point cloud
`p1_est` = p0 rotated to fit p1

Calling `plot_3d_point_cloud` on these should plot them ; however it might not work out of the box. IIRC, the point clouds in the PyTorch implementation are of a different shape (Bx3xN) than of the TensorFlow implementation one (BxNx3) where B is the batch size and N is the number of points. Also, I'm not sure if `plot_3d_point_cloud` expects a batch dimension. If not, plotting `p0[i]` should work for some index `i` ;

I hope these instructions are clear enough!
