### ISSUE TITLE
Improve README for registration task

### ISSUE THREAD

**Issue by YoruCathy** [itailang/SampleNet#2]
I tried to simply run the docker, following the instructions in readme, while an error occur, telling me that the file /workspace does not exist.
Then a series of errors occured, so that I have to manually clone the Pointnet2_Pytorch repo.
However, after I clone it, and placed it in the correct  path I suppose, which should be ./registration/workspace/Pointnet2_Pytorch, another error occured.
![image](https://user-images.githubusercontent.com/16759982/79013760-fba0fb00-7b9b-11ea-82d2-bb71ef91b07f.png)

Maybe some improvements of the install instructions in readme can be improved. That would be helpful.

**Comment by asafmanor** [comment]
There have been some non-backward-compatible changes in Pointnet2_PyTorch repository.
We have fixed the issue and suggest two solutions:
- Pulling our dev Docker image (linux / amd64)
- Building your own Docker image using the given updated Dockerfile. See [registration/README.md](https://github.com/itailang/SampleNet/blob/master/registration/README.md)
