### ISSUE TITLE
Reconstruction Use other data

### ISSUE THREAD

**Issue by ptxaxx** [itailang/SampleNet#20]
Hi! 
I implemented your reconstruction network, and the results are very good, but I want to use a model point cloud of my own for reconstruction sampling, that is to say, use your trained network to achieve downsampling of a point cloud? what should i do？

**Comment by itailang** [comment]
Hi @ptxaxx!
Please see the [README file](
https://github.com/itailang/SampleNet/blob/master/reconstruction/README.md) for the reconstruction task, which explains how to train SampleNet for that task.

**Comment by ptxaxx** [comment]
@itailang Thanks for your reply！
If I have point cloud data of a rabbit, how can I use the already trained samplenet to sample about the reconstruction！I don't know how to use this network to sample the rabbit.
Can you describe in detail

**Comment by itailang** [comment]
We assume that you have a model for reconstructing a rabbit. So first, you should have one. Then, you can train SampleNet to sample the rabbit for reconstructing it from less points.

**Comment by ptxaxx** [comment]
Sorry to bother you again！
     I want to sample a point cloud model using samplenet, such as a car or airplane or other point cloud models，but I don't know how to do it！May I ask how I can input a car point cloud, and then output a sampled point cloud？
Like this：
input：
![ce4c611c106c92841f13ce5f53cd571](https://user-images.githubusercontent.com/94749768/198949381-b722c656-5da5-44ca-967a-770d7b5a75d6.jpg)
output：
![b1f282bd7c9b751e0f2132ea419f14b](https://user-images.githubusercontent.com/94749768/198949485-6f440a6d-6045-42dc-a3ae-a34e155896fc.jpg)

A little fan is eager to get your help, I hope you can describe the operation in detail！
Thanks！！！

**Comment by itailang** [comment]
Dear @ptxaxx,

I appreciate you interest in my project very much. To sample a shape instance form a class that you want (as car, airplane, etc), you should first train an autoencoder for that class and then train SampleNet for sampling instances form that class using the freezed trained autoencoder. Note that you can also train a multi-class autoencoder and SampleNet.

For the training and evaluation commands, just follow the script [runner_samplenet.sh](https://github.com/itailang/SampleNet/blob/master/reconstruction/runner_samplenet.sh). Note that the autoencoder is set to multi-class of ["chair", "table", "car", "airplane"]. So, you can sample cars and airplanes with the resulting SampleNet.

Note the you may change the shape classes [here](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/reconstruction/autoencoder/train_ae.py#L58).

**Comment by ptxaxx** [comment]
Thank you very much！
