### ISSUE TITLE
Question about reflectivity

### ISSUE THREAD

**Issue by yeyBingo** [itailang/SampleNet#21]
Hello, your work has helped me a lot, but I encountered a problem in the process of using it. If I want to use the reflectivity information of the lidar, how can I preserve this feature during the SampleNet downsampling process?

**Comment by itailang** [comment]
Hi @yeyBingo,

Thank you for your interest in the work. Reflectivity influences the density of points. You may compute the local density per-point for the original point cloud (# of neighbors / # of point in the point cloud). Then, compute this measure for the sampled point cloud, and add a loss for preserving the local density for the optimization objective of SampleNet.

Please let me know if you have any further questions.
