### ISSUE TITLE
How to process my point cloud file with the network

### ISSUE THREAD

**Issue by barrym1** [itailang/SampleNet#22]
Hi,
I have trained and evaluated Sample Net for registration, and the result seems good. 
![QQ图片20230412170254](https://user-images.githubusercontent.com/113100863/231408419-2d2b176a-1159-42a0-8883-5e5bd4794cff.jpg)
But i don't know how to process my point cloud file(.txt or .ply) with the network, nor do I know how to output it and save it. Could you tell me what should i do? How to modify codes？
This will be very helpful to me, thanks a lot!

**Comment by itailang** [comment]
Hi @barrym1,

To see how the data is loaded, follow the variable `self.data_dir` in [modelnet_loader_torch](https://github.com/itailang/SampleNet/blob/master/registration/data/modelnet_loader_torch.py).

You can see the input and output data in the function [compute_pcrnet_loss](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/registration/main.py#L557). The sampled point clouds are `p0` and `p1` and the rotated point cloud is `p1_est`. You can find a point cloud visualization example [here](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/reconstruction/sampler/evaluate_samplenet.py#L156).
 
Good luck!

**Comment by barrym1** [comment]
Sorry, I still can't solve this problem, can you tell me the specific steps?I am very interested in your research.Thank you so much!

**Comment by itailang** [comment]
Can you explain what exactly the problem is?

**Comment by barrym1** [comment]
My problem is how to process my point cloud file(my_cloud.ply) with the network after training. Can you tell me the specific steps?

**Comment by itailang** [comment]
I assume that you already have the template (original) and source (rotated) point clouds in your file. They are denoted as $p_0$ and $p_1$, respectively.

1. Load your data. See the function [ _load_data_file](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/registration/data/modelnet_loader_torch.py#L25) for reference.
2. Feed the point clouds to SampleNet to sample them. See the function [compute_samplenet_loss](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/registration/main.py#L500) for reference.
3. Feed the sampled point clouds to the task network to compute the rotation for registration. See the function [compute_pcrnet_loss](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/registration/main.py#L557) for reference.
