### ISSUE TITLE
problem with dataloader

### ISSUE THREAD

**Issue by barrym1** [itailang/SampleNet#23]
What does 16 mean [here](https://github.com/itailang/SampleNet/blob/master/registration/data/modelnet_loader_torch.py)(line 141)？Why 16？Shouldn't the num_points for each point cloud file feeded be 1024?
Thank you for your answer.

**Comment by itailang** [comment]
Dear @barrym1,

Thank you for your question. The line you mentioned is a sanity check for the dataset class. For the actual usage of the class, the number of point is set according to the parameter `args.num_in_points`, as you can see in line 606 [here](https://github.com/itailang/SampleNet/blob/0db846fb3e3f3b8a738a78e77b7f11f5b544e9e9/registration/main.py#L606) for example.
