### ISSUE TITLE
classification

### ISSUE THREAD

**Issue by bhatipriyanka** [itailang/SampleNet#26]
How to use code for classification task. Means i have a existing model, optimizer etc but just want to change farthest point sampling to samplenet.

**Comment by itailang** [comment]
Dear @Pari0511,

As I understand, you have a trained classifier and would like to replace its FPS with SampleNet. In this case, freeze the classifier's parameters, replace FPS with SampleNet, and train it with the classifier's objective.

Let me know if you have any further questions.
