### ISSUE TITLE
Using the SampleNet for LiDAR pointcloud

### ISSUE THREAD

**Issue by Lelucermaire111** [itailang/SampleNet#27]
Hi!
Thank you for this impressive work. I'm interested in using the SampleNet to sample the task-aware points for LiDAR pointcloud. As we know, LiDAR pointcloud is sparse, not uniform and complex. Do you think this is feasible, or do you have any suggestions for me?

**Comment by itailang** [comment]
Dear @Lelucermaire111,

Thanks for your interest in our work!

**Comment by itailang** [comment]
Dear @Lelucermaire111,

Thanks for your interest in our work!

It is an interesting question. I think you can use the learned sampling concept but add hierarchy. For example, use a SampleNet over local regions of the point cloud to sample them. Then, if you want to lower the number of points further, unify the points from the local regions and run another SampleNet on that set.

Let me know if you have any further questions or thoughts.
