### ISSUE TITLE
Docker problem in registration

### ISSUE THREAD

**Issue by Micheal-K** [itailang/SampleNet#28]
Hi great author,

I would work on your code, here I have problem with docker environment. Must I install "Nvidia-Docker" in my system? not just in the docker container? because I have no access to operate the system files, so I can't install Nvidia-Docker in system layer. could I just install it in docker container? before I pull your docker ,what should I do? pleaes give me some advices, thanks alot

"
Installation
We strongly recommend working with [Docker Engine](https://hub.docker.com/search/?type=edition&offering=community) and [Nvidia-Docker](https://github.com/NVIDIA/nvidia-docker/tree/master). At this moment, the container can only run on a CUDA (linux/amd64) enabled machine due to specific compiled ops from [Pointnet2_PyTorch](https://github.com/erikwijmans/Pointnet2_PyTorch).

Pull and run the Docker container
docker pull asafmanor/pytorch:samplenetreg_torch1.4
docker run --runtime nvidia -v $(pwd):/workspace/ -it --name samplenetreg asafmanor/pytorch:samplenetreg_torch1.4
"

**Comment by itailang** [comment]
Hello @Micheal-K,

Thank you for your interest in our project.

Nvidia-Docker is required for accessing an Nvidia GPU from a Docker container. Maybe it is already installed on your system?

Anyway, you can try following our docker file and install a virtual environment instead.
