### ISSUE TITLE
Can not train "SampleNet.py " in registration.

### ISSUE THREAD

**Issue by zhangguanghui1** [itailang/SampleNet#4]
When I run "git checkout 5ff4382f56a8cbed2b5edd3572f97436271aba89", the error is as below:
**fatal: reference is not a tree: 5ff4382f56a8cbed2b5edd3572f97436271aba89**

However, when I skip the  "git checkout 5ff4382f56a8cbed2b5edd3572f97436271aba89", the error is as below: 
**CUDA kernel failed : no kernel image is available for execution on the device
void group_points_kernel_wrapper(int, int, int, int, int, const float*, const int*, float*) at L:38 in pointnet2/_ext-src/src/group_points_gpu.cu**

 Look forward to your help! Thank you very much!

**Comment by asafmanor** [comment]
Hi!
(1) First, try just using our Docker image, like recommended in the README.md
```sh
docker pull asafmanor/pytorch:samplenetreg_torch1.4
docker run --runtime nvidia -v $(pwd):/workspace/ -it --name samplenetreg asafmanor/pytorch:samplenetreg_torch1.4
```
And no additional steps should be taken.

(2) Alternatively, if you insist on building your own image:
I have checked your error and could not reproduce it. When cloning Pointnet2_PyTorch straight from GitHub https://github.com/erikwijmans/Pointnet2_PyTorch
I could easily run:
```sh
git checkout 5ff4382f56a8cbed2b5edd3572f97436271aba89
pip install -r requirements.txt
pip install -e .
```

I suppose you might have been in the wrong directory / project when executing "git checkout...".
If **our** docker image solution (details in (1)) does not work (can not see why, though. I'd appreciate you help in reproducing the bug if that happens), try manually cloning, checking out that specific commit, and installing PointNet2_PyTorch repository.

Hope it solves your problem! please keep me posted.

Thanks,
Asaf

**Comment by itailang** [comment]
Dear zhangguanghui1,

If you have further questions, you are welcome to reopen the issue.

Thank you!

**Comment by ptxaxx** [comment]
I also encountered this problem;
➜  / cd root
➜  ~ ls
Pointnet2_PyTorch
➜  ~ cd Pointnet2_PyTorch 
➜  Pointnet2_PyTorch git:(master) ✗ git checkout 5ff4382f56a8cbed2b5edd3572f97436271aba89
fatal: reference is not a tree: 5ff4382f56a8cbed2b5edd3572f97436271aba89
I do not how to slove it?  Can you help me? Thx!
