### ISSUE TITLE
i can't find  knn_cuda file 

### ISSUE THREAD

**Issue by hay-001** [itailang/SampleNet#5]
hi, where can i find  the knn_cuda file ? thanks

**Comment by asafmanor** [comment]
Hi,
KNN_CUDA is not a file, but a library installed using pip:
`pip install --upgrade https://github.com/unlimblue/KNN_CUDA/releases/download/0.2/KNN_CUDA-0.2-py3-none-any.whl`

The github repository can be found here:
https://github.com/unlimblue/KNN_CUDA/

Closing, please reopen if further issues come up on this subject.
