### ISSUE TITLE
So.tf_approxmatch_so.so

### ISSUE THREAD

**Issue by ZhangYi0810** [itailang/SampleNet#8]
Could you please show me the tf_approxmatch_so.so and other so.so

**Comment by itailang** [comment]
Hello @Yerless,

Please use the [compilation script](https://github.com/itailang/SampleNet/blob/master/classification/compile_ops.sh) to create the so files.

**Comment by ZhangYi0810** [comment]
@itailang  Thanks! I got the _so.so yet.
