### ISSUE TITLE
Classification Accuracy

### ISSUE THREAD

**Issue by ZhangYi0810** [itailang/SampleNet#9]
Could you please show me the specific data about the classification when sampling with SampleNet，because I found SampleNet64 and SampleNet32 have the same Classification Accuracy.

The classification accuracy is eval accuracy during training or eval accuracy in the evaluate_samplenet.py?

I also found the eval accuracy during training is 3% higher than the eval accuracy in the evaluate_samplenet.py.

The paper says that after training the S-NET model or SampleNet model,it will use the trained model parameters to train the classification network, but the code does not,could you please give me some advices?

I'm looking forward to your reply！ @itailang @asafmanor

**Comment by itailang** [comment]
Hello @Yerless,

I appreciate you interest in our work!

The accuracy with SampleNet for classification is as reported in Figure 5 in the paper. It is the accuracy obtained with [evaluate_samplenet.py](https://github.com/itailang/SampleNet/blob/master/classification/evaluate_samplenet.py).

The classifier should be trained first. Then it is kept freeze during the training of SampleNet. The script [runner_samplenet.sh](https://github.com/itailang/SampleNet/blob/master/classification/runner_samplenet.sh) shows a run example of this pipeline. You are welcome to use it!

Please do not hesitate to ask further questions if any.

**Comment by ZhangYi0810** [comment]
Thank you.
If I have other questions, I will keep in touch with you.

**Comment by chenxl124578** [comment]
> Could you please show me the specific data about the classification when sampling with SampleNet，because I found SampleNet64 and SampleNet32 have the same Classification Accuracy.
> 
> The classification accuracy is eval accuracy during training or eval accuracy in the evaluate_samplenet.py?
> 
> I also found the eval accuracy during training is 3% higher than the eval accuracy in the evaluate_samplenet.py.
> 
> The paper says that after training the S-NET model or SampleNet model,it will use the trained model parameters to train the classification network, but the code does not,could you please give me some advices?
> 
> I'm looking forward to your reply！ @itailang @asafmanor

yes, i also find the question about '' the eval accuracy during training is 3% higher than the eval accuracy in the evaluate_samplenet.py.''

I got 83.5 eval acc during training and got 80 eval acc in evaluate_samplenet.py with match_output=1.
I think maybe i will get 83.5 eval acc when I set match_output=0, but the result is 84.6. 

i wonder the reason why i got the result that 83.5 eval acc during training, 80 eval acc and 84.6 eval acc in evaluate_samplenet.py.

I'm looking forward to your reply! Thank you!

**Comment by itailang** [comment]
Dear @chenxl124578,

Please see my answer to issue #17. Thank you!

**Comment by chenxl124578** [comment]
> 

Thanks a lot!

**Comment by chenxl124578** [comment]
> Dear @chenxl124578,
> 
> Please see my answer to issue #17. Thank you!

Sorry, i just get another question :)

I got 83.5 eval acc during training and 84.6 eval acc in evaluate_samplenet.py with match_output=0, does it mean that Soft Projection has a negative boost to the model?

**Comment by itailang** [comment]
No. The matching operation (match_oputput=1) is the cause for some performance reduction. We used the matching in our work, since we were interested in sampling original points from the input point cloud.

**Comment by chenxl124578** [comment]
> 

That really helpful for me! Thank for your reply!

**Comment by itailang** [comment]
Great, thank you for sharing that!
